image: node:carbon
stages:
  - install

install-dependencies:
  stage: install
  script:
     - apt update && apt-get python make g++
     - apt-get nodejs npm
     - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/