version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nodejs-cloudbuilder-api
        env_file: 
            - .env
        ports: 
            - "8081:8080"